export const FAVORITE_ACTIONS_TYPES = {
	FETCH_FAVORITE_ITEMS_START: "FAVORITE/FETCH_FAVORITE_ITEMS_START",
	FETCH_FAVORITE_ITEMS_SUCCESS: "FAVORITE/FETCH_FAVORITE_ITEMS_SUCCESS",
	FETCH_FAVORITE_ITEMS_FAILED: "FAVORITE/FETCH_FAVORITE_ITEMS_FAILED",
	POST_FAVORITE_ITEMS_START: "FAVORITE/POST_FAVORITE_ITEMS_START",
	POST_FAVORITE_ITEM_SUCCESS: "FAVORITE/POST_FAVORITE_ITEM_SUCCESS",
	POST_FAVORITE_ITEM_FAILED: "FAVORITE/POST_FAVORITE_ITEM_FAILED",
};
