export const Videos_ACTIONS_TYPES = {
	FETCH_VIDEOS_START: "VIDEOS_MODEL/ FETCH_DETAILS_START",
	FETCH_VIDEOS_SUCCESS: "VIDEOS_MODEL/FETCH_VIDEOS_SUCCESS",
	FETCH_VIDEOS_FAILED: "VIDEOS_MODEL/FETCH_VIDEOS_FAILED",
};
