export const TRENDING_ACTIONS_TYPES = {
	FETCH_TRENDING_START: "HOME/FETCH_TRENDING_START",
	FETCH_TRENDING_SUCCESS: "HOME/FETCH_TRENDING_SUCCESS",
	FETCH_TRENDING_FAILED: "HOME/FETCH_TRENDING_FAILED",
};
