export const DETAILS_ACTIONS_TYPES = {
	FETCH_DETAILS_START: "DETAILS/ FETCH_DETAILS_START",
	FETCH_MOVIE_DETAILS_SUCCESS: "DETAILS/FETCH_MOVIE_DETAILS_SUCCESS",
	FETCH_SERIES_DETAILS_SUCCESS: "DETAILS/FETCH_SERIES_DETAILS_SUCCESS",
	FETCH_DETAILS_FAILED: "DETAILS/FETCH_MOVIES_FAILED",
};
